# Generated by Django 5.0.3 on 2024-04-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_checklist_checklisttemplate_checklisttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text="Formatted as 'app_label:model'", max_length=100)),
                ('pk_int', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pk_uuid', models.UUIDField(blank=True, null=True)),
                ('pk_char', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_objects', related_query_name='object', to='helpdesk.ticket')),
            ],
        ),
    ]
